[program:php-fpm]
command=/bin/bash -c "mkdir -p /var/run/php && chown -R www-data:www-data /var/run/php && php-fpm -F"
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm.err
