; 'zzz' seria para ser carregado por último

file_uploads = On
upload_max_filesize = 100M
post_max_size = 120M
max_file_uploads = 20

memory_limit = 512M
max_execution_time = 360
max_input_time = 120
